[workspace]
members = ["bot", "core"]
resolver = "3"

[workspace.dependencies]
neobabu-core = { path = "core" }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"