owner_ids = []

[emojis]
arrow_back = 0
arrow_left = 0
arrow_right = 0
arrow_double_left = 0
arrow_double_right = 0
balloon_red = 0
clock = 0
face_angry = 0
face_angry_evil = 0
face_anguished = 0
face_anxious_sweat = 0
face_astonished = 0
face_beaming_smile = 0
face_blowing_kiss = 0
face_clouds = 0
face_clown = 0
face_cold = 0
face_confounded = 0
face_confused_sad = 0
face_cool = 0
face_cowboy_hat = 0
face_crying = 0
face_cursing = 0
face_diagonal_mouth = 0
face_disappointed = 0
face_disguised = 0
face_dizzy = 0
face_dotted_line = 0
face_downcase = 0
face_drooling = 0
face_exhaling = 0
face_exploding = 0
face_expressionless = 0
face_fearful = 0
face_flushed = 0
face_frowning_open = 0
face_frowning_slight = 0
face_frowning = 0
face_grimacing = 0
face_grinning_big_eyes = 0
face_grinning_smiling = 0
face_grinning_squinting = 0
face_grinning_sweat = 0
face_grinning = 0
face_halo = 0
face_hand_over_mouth_eyes = 0
face_hand_over_mouth = 0
face_head_bandage = 0
face_heart_eyes = 0
face_hearts = 0
face_holding_tears = 0
face_hot = 0
face_hugging = 0
face_hushed = 0
face_ill = 0
face_joy_tears = 0
face_kissing_closed = 0
face_kissing_smiling = 0
face_kissing = 0
face_lying = 0
face_medical_mask = 0
face_melting = 0
face_mewing = 0
face_money = 0
face_monocle = 0
face_nauseated = 0
face_nerd = 0
face_neutral = 0
face_no_mouth = 0
face_open_mouth = 0
face_partying = 0
face_peeking_eye = 0
face_pensive = 0
face_persevering = 0
face_pleading = 0
face_poo = 0
face_pouting = 0
face_raised_eyebrow = 0
face_relieved = 0
face_robot = 0
face_rofl = 0
face_rolling_eyes = 0
face_sad_relieved = 0
face_saluting = 0
face_savoring = 0
face_screaming_fear = 0
face_shake_no = 0
face_shake_yes = 0
face_shaking = 0
face_shushing = 0
face_skull = 0
face_sleeping = 0
face_sleepy = 0
face_smiling_blush = 0
face_smiling_evil = 0
face_smiling_slight = 0
face_smiling = 0
face_smirking = 0
face_sneezing = 0
face_sobbing = 0
face_spiral_eyes = 0
face_star_struck = 0
face_tear = 0
face_thinking = 0
face_tired = 0
face_tongue_squinting = 0
face_tongue = 0
face_triumphant = 0
face_unamused = 0
face_upside_down = 0
face_vomiting = 0
face_weary = 0
face_winking_tongue = 0
face_winking = 0
face_woozy = 0
face_worried = 0
face_yawning = 0
face_zany = 0
face_zipper_mouth = 0
friends = 0
maple_leaf = 0
paper = 0
purple_flower = 0
pvp = 0
rock = 0
scissors = 0
snowflake = 0
sparkle = 0
stats = 0
sun = 0
trophy = 0