[package]
name = "neobabu-core"
version = "0.1.0"
edition = "2024"
description = "The core library containing all of neobabu's main logic."

[dependencies]
migration = { path = "migration" }
sea-orm = { version = "2.0.0-rc.16", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-cron-scheduler = "0.15.1"
tracing = { workspace = true }
futures = "0.3.31"