[package]
name = "neobabu-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
neobabu-core = { workspace = true }
poise = "0.6.1"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }